// <auto-generated />
namespace AirHelp.DAL.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remane : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remane));
        
        string IMigrationMetadata.Id
        {
            get { return "201803301520001_remane"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
