// <auto-generated />
namespace AirHelp.DAL.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename));
        
        string IMigrationMetadata.Id
        {
            get { return "201803301451353_rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
